import * as cdk from 'aws-cdk-lib'
import * as iam from 'aws-cdk-lib/aws-iam'
import * as route53 from 'aws-cdk-lib/aws-route53'
import { Construct } from 'constructs'
import { cleanDomainName, cleanHostedZoneId } from './utils'

export interface CrossAccountValidationRoleProps {
  /**
   * The AWS account IDs that are allowed to assume this role for DNS validation.
   *
   * These are the accounts where the ``DnsValidatedCertificate`` construct is deployed.
   */
  readonly trustedAccounts: string[]

  /**
   * The Route53 hosted zones that the role is allowed to modify for certificate validation.
   *
   * The role will be granted ``route53:ChangeResourceRecordSets`` permission on these zones,
   * restricted to CNAME record types with UPSERT and DELETE actions only.
   */
  readonly hostedZones: route53.IHostedZone[]

  /**
   * Domain names or wildcard patterns that the role is allowed to create validation records for.
   *
   * Each entry should be a domain name (e.g. ``example.com``) or a wildcard domain
   * (e.g. ``*.example.com``). For each domain, the role is allowed to create the ACM
   * validation CNAME record (``_<hash>.domain``) as well as wildcard variants.
   *
   * If not specified, the role is allowed to create validation records for any domain
   * within the given hosted zones. It is recommended to specify this to further
   * restrict the role's permissions.
   *
   * @default - Allow validation records for any domain in the hosted zones.
   */
  readonly allowedDomainNames?: string[]

  /**
   * The name of the IAM role.
   *
   * @default - Auto-generated by CloudFormation.
   */
  readonly roleName?: string

  /**
   * External ID for additional security when assuming the role.
   *
   * When set, the assuming principal must provide this external ID.
   *
   * @default - No external ID required.
   */
  readonly externalId?: string
}

/**
 * An IAM role for cross-account certificate DNS validation.
 *
 * This role should be deployed in the account that owns the Route53 hosted zones.
 * The ``DnsValidatedCertificate`` construct in the certificate account will assume
 * this role to create and delete DNS validation records.
 *
 * Extends ``iam.Role`` directly, so it can be customized with additional policies
 * or passed anywhere an ``iam.IRole`` is accepted.
 *
 * @example
 *
 * const hostedZone = route53.HostedZone.fromHostedZoneAttributes(this, 'HostedZone', {
 *   hostedZoneId: 'Z1234567890',
 *   zoneName: 'example.com',
 * })
 *
 * const validationRole = new CrossAccountValidationRole(this, 'ValidationRole', {
 *   trustedAccounts: ['123456789012'],
 *   hostedZones: [hostedZone],
 *   allowedDomainNames: ['example.com', '*.example.com'],
 * })
 */
export class CrossAccountValidationRole extends iam.Role {
  constructor(scope: Construct, id: string, props: CrossAccountValidationRoleProps) {
    if (props.trustedAccounts.length === 0) {
      throw new Error('At least one trusted account must be provided')
    }

    if (props.hostedZones.length === 0) {
      throw new Error('At least one hosted zone must be provided')
    }

    const principals = props.trustedAccounts.map((accountId) => new iam.AccountPrincipal(accountId))
    const compositePrincipal = principals.length === 1 ? principals[0] : new iam.CompositePrincipal(...principals)

    super(scope, id, {
      roleName: props.roleName,
      assumedBy: compositePrincipal,
      externalIds: props.externalId ? [props.externalId] : undefined,
    })

    // route53:GetChange does not support resource-level permissions
    this.addToPolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: ['route53:GetChange'],
        resources: ['*'],
      })
    )

    // Grant ChangeResourceRecordSets per hosted zone with restrictive conditions
    for (const zone of props.hostedZones) {
      const hostedZoneId = cdk.Token.isUnresolved(zone.hostedZoneId)
        ? zone.hostedZoneId
        : cleanHostedZoneId(zone.hostedZoneId)

      const conditions: Record<string, Record<string, string[]>> = {
        'ForAllValues:StringEquals': {
          'route53:ChangeResourceRecordSetsRecordTypes': ['CNAME'],
          'route53:ChangeResourceRecordSetsActions': ['UPSERT', 'DELETE'],
        },
      }

      if (props.allowedDomainNames && props.allowedDomainNames.length > 0) {
        const normalizedPatterns = this.buildValidationRecordPatterns(props.allowedDomainNames)
        conditions['ForAllValues:StringLike'] = {
          'route53:ChangeResourceRecordSetsNormalizedRecordNames': normalizedPatterns,
        }
      }

      this.addToPolicy(
        new iam.PolicyStatement({
          effect: iam.Effect.ALLOW,
          actions: ['route53:ChangeResourceRecordSets'],
          resources: [`arn:aws:route53:::hostedzone/${hostedZoneId}`],
          conditions,
        })
      )
    }
  }

  /**
   * Build validation record name patterns from the allowed domain names.
   *
   * ACM creates validation CNAMEs like ``_<hash>.<domain>``. For wildcard certificates
   * (``*.example.com``), the validation record is ``_<hash>.example.com`` (without the wildcard).
   *
   * We generate patterns like ``_*.example.com`` to allow any ACM validation hash while
   * restricting to the specified domains.
   *
   * Override this method to customize the validation record name patterns.
   */
  protected buildValidationRecordPatterns(domainNames: string[]): string[] {
    const patterns = new Set<string>()
    for (const domain of domainNames) {
      const cleaned = cleanDomainName(domain)
      // Strip wildcard prefix if present — ACM validation records for *.example.com
      // are created at _<hash>.example.com, not _<hash>.*.example.com
      const baseDomain = cleaned.startsWith('*.') ? cleaned.slice(2) : cleaned
      // Allow any ACM validation hash prefix
      patterns.add(`_*.${baseDomain}`)
    }
    return Array.from(patterns)
  }
}
